#!/usr/bin/env python3
# 词级对齐 —— Whisper 识别配音 → 逐字时间戳写回 src/timing.ts + 重写 SCENES 时长
# 核心：Whisper 给「词」时间戳、字幕按「字」渲染——difflib 把识别文本软对齐回配音稿
# （TTS 会把「95%」念成「百分之九十五」、漏字多字常见，硬匹配必死），再把词时间均摊到字。
# 用法：PROJECT=/path/to/project AUDIO_OUT=/path/to/audio python3 sync-timing.py
# 依赖：pip install openai-whisper ffmpeg-python（或直接 ffprobe）
import os, re, subprocess, difflib
import whisper

ROOT = os.environ.get("PROJECT", os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "template"))
OUT_DIR = os.environ.get("AUDIO_OUT", f"{ROOT}/public/audio")
TIMING_FILE = os.environ.get("TIMING_FILE", f"{ROOT}/src/timing.ts")
CONSTANTS_FILE = os.environ.get("CONSTANTS", f"{ROOT}/src/constants.ts")
CROSSFADE = 0.5   # 场景间交叉淡化余量（秒）
MODEL = os.environ.get("WHISPER_MODEL", "small")  # tiny/base/small…越大越准越慢

src = open(CONSTANTS_FILE, encoding="utf-8").read()
SCENES = re.findall(r'(\w+):\s*\{\s*text:\s*"([^"]+)",\s*emo:', src)
assert SCENES, "VO parse failed: constants.ts 里找不到 name: {text, emo} 结构"
ORDER = [n for n, _ in SCENES]
EXPECTED = dict(SCENES)


def dur(mp3):
    return float(subprocess.check_output(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", mp3]).strip())


def chars_of(text):
    # 切分单位：CJK 逐字；连续 ASCII 当一个单位（避免 "VIP" 被拆成 V-I-P）
    out, buf = [], ""
    for ch in text:
        if ord(ch) < 128 and ch not in "，。！？；：、":
            buf += ch
        else:
            if buf:
                out.append(buf); buf = ""
            out.append(ch)
    if buf:
        out.append(buf)
    return out


def norm(s):
    return re.sub(r"[\s，。！？；：、,.!?;:'\"—…·\-]", "", s)


def expected_char_times(scene, words_ts, exp_units):
    exp_str = norm("".join(exp_units))
    rec_words = []
    rec_str = ""
    for w in words_ts:
        t = norm(w["word"])
        if t:
            rec_words.append((t, float(w["start"]), float(w["end"])))
            rec_str += t
    if not rec_words:  # 识别为空：均匀摊派兜底
        step = dur(f"{OUT_DIR}/{scene}.mp3") / len(exp_units)
        return [(u, i * step, (i + 1) * step) for i, u in enumerate(exp_units)]

    # rec_str 每个字符 → exp_str 哪个字符（SequenceMatcher 软对齐）
    sm = difflib.SequenceMatcher(None, rec_str, exp_str, autojunk=False)
    r2e = [None] * len(rec_str)
    for tag, a1, a2, b1, b2 in sm.get_opcodes():
        if tag == "equal":
            for i in range(a2 - a1):
                r2e[a1 + i] = b1 + i
        elif tag == "replace":
            for i in range(a2 - a1):
                r2e[a1 + i] = b1 + int(round(i * (b2 - b1) / max(a2 - a1, 1)))
                r2e[a1 + i] = min(r2e[a1 + i], b2 - 1)
    for i in range(len(r2e)):
        if r2e[i] is None:
            r2e[i] = (r2e[i - 1] if i and r2e[i - 1] is not None else 0)

    # 词时间均摊到该词对齐上的期望字符
    rec_pos = 0
    char_time = [None] * len(exp_str)
    for t, ws, we in rec_words:
        idxs = [r2e[rec_pos + i] for i in range(len(t))]
        rec_pos += len(t)
        idxs = sorted(set(i for i in idxs if i is not None and i < len(exp_str)))
        n = len(idxs)
        for k, ei in enumerate(idxs):
            char_time[ei] = (ws + (we - ws) * k / n, ws + (we - ws) * (k + 1) / n)
    for i in range(len(char_time)):
        if char_time[i] is None:
            char_time[i] = char_time[i - 1] if i else (0.0, 0.05)

    # exp 单位（字/ASCII 块）→ 起止时间；标点挂靠前字并留 0.12s 断句余韵
    out, ci = [], 0
    PUNCT = r"[\s，。！？；：、,.!?;:'\"—…·\-]"
    for u in exp_units:
        n = sum(1 for ch in u if not re.match(PUNCT, ch))
        if n == 0:
            t0 = out[-1][2] if out else 0.0
            out.append((u, t0, t0 + 0.12))
            continue
        first = char_time[ci]; ci += n - 1
        last = char_time[ci]; ci += 1
        out.append((u, first[0], max(last[1], first[0] + 0.05)))
    return out


model = whisper.load_model(MODEL)
lines = ["// GENERATED by sync-timing.py —— Whisper 词级时间戳逐字对齐到配音稿，勿手改",
         "",
         "export const AUDIO_TIMING: Record<string, { duration: number; words: Array<{ text: string; start: number; end: number }> }> = {"]

all_dur = {}
for scene in ORDER:
    wav = f"{OUT_DIR}/{scene}.wav"
    mp3 = f"{OUT_DIR}/{scene}.mp3"
    src_audio = wav if os.path.exists(wav) else mp3
    r = model.transcribe(src_audio, language="zh", word_timestamps=True, condition_on_previous_text=False)
    words_ts = [w for seg in r["segments"] for w in (seg.get("words") or [])]
    d = dur(mp3)
    all_dur[scene] = d
    units = expected_char_times(scene, words_ts, chars_of(EXPECTED[scene]))
    print(f"{scene}: {len(words_ts)} whisper words -> {len(units)} units, dur={d:.2f}s")
    lines.append(f"  '{scene}': {{")
    lines.append(f"    duration: {d:.6f},")
    lines.append("    words: [")
    for c, s, e in units:
        c_esc = c.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"      {{ text: '{c_esc}', start: {s:.3f}, end: {e:.3f} }},")
    lines.append("    ],")
    lines.append("  },")
lines.append("};")
open(TIMING_FILE, "w").write("\n".join(lines) + "\n")
print("timing.ts written")

# ---- 重写 SCENES：start 依次排（前一场景尾与后一场景头重叠 CROSSFADE 做交叉淡化）----
start = 0.0
entries = []
for name in ORDER:
    dd = round(all_dur[name] + CROSSFADE, 1)
    entries.append(f"  {name}: {{ start: {round(start, 1)}, dur: {dd} }},")
    print(f"{name}: start={round(start,1)}, dur={dd}")
    start = round(start + dd - CROSSFADE, 1)
block = ("export const SCENES: Record<string, { start: number; dur: number }> = {\n"
         + "\n".join(entries) + "\n};")
src2 = re.sub(r"export const SCENES:[^=]*=\s*\{.*?\n\};", block, src, flags=re.DOTALL, count=1)
assert src2 != src, "SCENES block not replaced"
open(CONSTANTS_FILE, "w").write(src2)
print("constants.ts SCENES rewritten")
